#pragma once

#include "NativeGameplayTags.h"

namespace GLDGameplayTag
{

	GLD_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
	
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);
	
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Melee);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_1);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_2);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_3);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_4);
	
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
	
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	GLD_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

};